version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_container
    network_mode: host
    command: ["sh", "-c", "./server"]

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_container
    network_mode: host
    depends_on:
      - server
    command: ["sh", "-c", "./client"]
